steps:
- name: 'docker'
  args: ['build', '-t', 'asiagcr.io/$PROJECT_ID/gcpproject','.']

images:
- 'asiagcr.io/$PROJECT_ID/gcpproject'

logging: CLOUD_LOGGING_ONLY  # or NONE if you don’t want logs at all
