steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/gcp-project-dev", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/gcp-project-dev"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=gke.yaml
  - --image=gcr.io/$PROJECT_ID/gcp-project-dev
  - --location=asia-south1-a
  - --cluster=gcp-devops-project
  - --namespace=gcp-devops-dev

options:
  logging: CLOUD_LOGGING_ONLY  # Ensures logs go to Cloud Logging
