steps:
- name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpproject','.']

images:
- 'gcr.io/$PROJECT_ID/gcpproject'

options:
  logging: CLOUD_LOGGING_ONLY  # Correct placement under `options`
